---
- name: ensure databases exist
  postgresql_db:
    login_host: "{{ item.host | default(pg_host) }}"
    port: "{{ item.port | default(pg_port) }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password | default(omit) }}"
    name: "{{ item.name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  with_items: "{{ pg_databases }}"
  when:
    - "pg_databases | length > 0"

- name: ensure pg users exist
  postgresql_user:
    login_host: "{{ item.host | default(pg_host) }}"
    port: "{{ item.port | default(pg_port) }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password | default(omit) }}"
    db: "{{ item.db }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
  with_items:
    - "{{ pg_users }}"
  when:
    - "pg_users | length > 0"

- name: grant all privileges on db to pg user
  postgresql_privs:
    login_host: "{{ item.host | default(pg_host) }}"
    port: "{{ item.port | default(pg_port) }}"
    login_user: "{{ pg_admin_user }}"
    login_password: "{{ pg_admin_password | default('omit') }}"
    db: "{{ item.db }}"
    type: schema
    objs: public
    privs: All
    roles: "{{ item.name }}"
  with_items:
    - "{{ pg_users }}"
  when:
    - "pg_users | length > 0"
